# Generated by Django 6.1 on 2026-08-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=20)),
                ('service_required', models.CharField(choices=[('routine_maintenance', 'Routine Maintenance'), ('engine_diagnostics', 'Engine Diagnostics'), ('brake_service', 'Brake Service'), ('tire_service', 'Tire Service'), ('battery_service', 'Battery Service'), ('air_conditioning', 'Air Conditioning'), ('suspension_steering', 'Suspension & Steering'), ('other', 'Other')], max_length=50)),
                ('problem_description', models.TextField(blank=True)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (08:00–12:00)'), ('afternoon', 'Afternoon (12:00–16:00)'), ('evening', 'Evening (16:00–18:00)'), ('no_preference', 'No Preference')], default='no_preference', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
